export const NEW_WORD = 'NEW_WORD'
export const SET_WORD_LEN = 'SET_WORD_LEN'
export const RIGHT_ATTEMPT = 'RIGHT_ATTEMPT'
export const BAD_ATTEMPT = 'BAD_ATTEMPT'
export const RESET_ATTEMPTS = 'RESET_ATTEMPTS'
export const SET_LIGHT_THEME = 'SET_LIGHT_THEME'
export const SET_DARK_THEME = 'SET_DARK_THEME'
export const SET_LEFT_TIME = 'SET_LEFT_TIME'
